# Site settings
title: Veaceslav Gaidarji
description: "I'm a software developer with main focus on Android platform. "
url: 'http://blog.vgaidarji.me'
baseurl: '/'
google_analytics: 'UA-74115810-1'
disqus_shortname: 'vgaidarji'
simple_search: https://www.google.com/search
subscribe_rss: /atom.xml
#excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
#excerpt_separator: "<!--more-->"
#titlecase: true       # Converts page and post titles to titlecase

author:
  name: 'Veaceslav Gaidarji'
  email: veaceslav.gaidarji@gmail.com
  facebook_username: 100001320317153
  github_username:  vgaidarji
  linkedin_username: veaceslavgaidarji
  stackoverflow: veaceslav-gaidarji

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
