# Site settings
title: Veaceslav Gaidarji
description: "I'm software developer with main focus on Android platform. "
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Veaceslav Gaidarji'
  email: veaceslav.gaidarji@gmail.com
  twitter_username:
  facebook_username:
  github_username:  donvigo
  linkedin_username:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
